baseURL = 'https://sspphamburglawnfete.org/'
languageCode = 'en-us'
title = 'SS. Peter & Paul Lawn Fete'
disableKinds = ["section", "taxonomy", "term"]

[params]
  description = "Join us for St. Peter & Paul's Annual Lawn Fete"

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
[module]
  [module.hugoVersion]
    min = "0.147.8"
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
